# Generated by Django 5.2.16 on 2026-07-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Краткое и понятное название продукта', max_length=200, verbose_name='Название товара')),
                ('description', models.TextField(help_text='Подробное описание характеристик и преимуществ', verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, help_text='Стоимость товара с точностью до копеек', max_digits=10, verbose_name='Цена (₽)')),
                ('image', models.ImageField(blank=True, help_text='Фотография товара (рекомендуется 1:1 или 4:3)', null=True, upload_to='products/%Y/%m/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически заполняется при создании', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
